name: account_domain

## To use the module just as an individual library
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.6

  ## https://pub.dev/packages/get
  get:
  get_storage:

  # App modules
  account_data:
    path: ../account_data
  # database_domain:
  #   path: ../database_domain
  # chat_domain:
  #   path: ../chat_domain
  core:
    path: ../core
  locator:
    path: ../locator
