name: core

## To use the module just as an individual library
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  ## https://pub.dev/packages/get
  get: ^4.6.5
  get_storage: ^2.0.3

  # Firebase
  cloud_firestore: ^3.1.6
  firebase_analytics: ^9.1.12
  firebase_storage: ^10.2.17
  firebase_remote_config: ^2.0.11
  cloud_functions: ^3.2.16

  connectivity_plus: ^2.3.5
  flutter_svg: ^1.1.1+1
  flutter_widget_from_html_core: ^0.8.5+3
  lottie: ^1.3.0

  # App modules
  account_domain:
    path: ../account_domain
  locator:
    path: ../locator
    
  font_awesome_flutter: ">=9.0.0"

flutter:
  uses-material-design: true
  