name: account_presentation

## To use the module just as an individual library
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  ## https://pub.dev/packages/get
  get:
  get_storage:

  ## Firebase
  cloud_firestore: ^3.1.6
  
  flutter_signin_button: ^2.0.0
  
  # App modules
  account_domain:
    path: ../account_domain
  core:
    path: ../core
  # locator:
  #   path: ../locator
  # router:
  #   path: ../router
    
  font_awesome_flutter: ">=9.0.0"
    
flutter:
  uses-material-design: true