name: account_data

## To use the module just as an individual library
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.17

  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0

  ## https://pub.dev/packages/get
  get:
  get_storage:

  # App modules
  account_domain:
    path: ../account_domain
  core:
    path: ../core
  locator:
    path: ../locator
